services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=social_identity'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
    volumes:
      - mysqldb:/var/lib/mysql/
    networks:
        - mynet
    ports:
      - '3306:3306'
